import Head from "next/head"
import React from "react"
import styles from "@/styles/page.module.css"

export default function Gif() {
	return (
		<>
			<Head>
				<title>MJB Boilerplate Gif Page route example</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>{"gif to go here"}</main>
		</>
	)
}
