import Head from "next/head"
import { Arimo } from "next/font/google"
import styles from "@/styles/Home.module.css"
import { GitHubLink, Header } from "@/components"

//replace with google font of choice
const arimo = Arimo({ subsets: ["latin"] })

export default function Home() {
	return (
		<>
			<Head>
				<title>MJB Boilerplate</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.main} ${arimo.className}`}>
				<Header
					title={"🍽️ MJB Boilerplate"}
					subTitle={
						"React app quickstart with Next.js, TypeScript, CSS Modules, React Testing Library, and React Query"
					}
				/>
				<footer className={styles.footer}>
					<GitHubLink link={"https://github.com/MollyJeanB/mjb-boilerplate"} />
				</footer>
			</main>
		</>
	)
}
